### PR TITLE
179: make D real

### LINKED ISSUE #179: Can't set `D` to `Inf`
**To reproduce**

``` r
library("primarycensored")
pcd_model <- pcd_cmdstan_model()
data <- data.frame(
  delay = c(1, 2, 3),
  delay_upper = c(2, 3, 4),
  n = c(10, 20, 15),
  pwindow = c(1, 1, 2),
  relative_obs_time = c(Inf, Inf, Inf)
)
stan_data <- pcd_as_stan_data(
  data,
  dist_id = 1,
  primary_id = 1,
  param_bounds = list(lower = c(0, 0), upper = c(10, 10)),
  primary_param_bounds = list(lower = numeric(0), upper = numeric(0)),
  priors = list(location = c(1, 1), scale = c(1, 1)),
  primary_priors = list(location = numeric(0), scale = numeric(0))
)
pcd_model$sample(data = stan_data)
#> Warning: A non-integer value was supplied for 'D'! It will be truncated to an
#> integer.
#> Warning in mde(x): NAs introduced by coercion to integer range
#> Error: Variable 'D' has NA values.
```

<sup>Created on 2024-12-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by sbfnk**
## Description

This PR closes #179 by defining D as real allowing it to be Inf.

[Describe the changes that you made in this pull request.]

## Checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [X] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [X] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [X] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
Good catch I think a future feature/issue should be to make d, pwindow, and d_upper real as well and check this is supported as this could in theory be something someone might want to do

Can you please add a news item and if not done in the other PR add yourself as a contributor

I think ideally this would have a test to avoid it happening in the future. If you feel like it could you add?

File: tests/testthat/test-pcd_cmdstan_model.R [hunk 1]
```diff
@@ -342,3 +342,72 @@ test_that(
...
+    priors = list(location = c(0, 1), scale = c(1, 1)),
+    primary_priors = list(location = numeric(0), scale = numeric(0))
+  )
+
+  # Fit model
+  model <- suppressMessages(suppressWarnings(pcd_cmdstan_model()))
+  fit <- suppressMessages(suppressWarnings(model$sample(
+    data = stan_data,
+    seed = 123,
+    chains = 4,
```
Comment (seabbs) [inline tests/testthat/test-pcd_cmdstan_model.R:391]:
```suggestion
    chains = 2,
```

File: tests/testthat/test-pcd_cmdstan_model.R [hunk 2]
```diff
@@ -342,3 +342,72 @@ test_that(
...
+    parallel_chains = 4,
```
Comment (seabbs) [inline tests/testthat/test-pcd_cmdstan_model.R:392]:
```suggestion
    parallel_chains = 2
```

**Review by seabbs — APPROVED** [review]
Nice LGTM. I used fewer cores and chains in the tests and made the news update a bit more specific.
